meta_product_name: "Travely"
meta_title: "Travely - travel easy and light with travely!"
meta_description: "Travely is a platform that helps travellers share items."
meta_image: "Final-logo.png"                       # should exist in `app/assets/images/`
